#ifndef GFX_HEADER_H_
#define GFX_HEADER_H_
// Autogenerated from build script


#include "bank10.h"

#include "bank2.h"

#include "bank3.h"

#include "bank4.h"

#include "bank5.h"

#include "bank6.h"

#include "bank7.h"

#include "bank8.h"

#include "bank9.h"

#include "gfxTileCount.h"

#endif
