#ifndef GFX_TILE_COUNT_H_
#define GFX_TILE_COUNT_H_
// Autogenerated from build script


#define Tile_Animated_TILECOUNT 417

#define Winner_5_2_TILECOUNT 364

#define Winner_6_2_TILECOUNT 364

#define p2_grow_anim_1_TILECOUNT 16

#define p1_idle_anim_1_TILECOUNT 20

#define p1_grow_anim_3_TILECOUNT 16

#define Winner_1_1_TILECOUNT 342

#define Winner_2_1_TILECOUNT 383

#define Winner_4_2_TILECOUNT 362

#define p3_idle_anim_3_TILECOUNT 20

#define Winner_3_1_TILECOUNT 415

#define MenuCursor2_TILECOUNT 12

#define PlayerSelectBacking_TILECOUNT 64

#define p1_idle_anim_2_TILECOUNT 20

#define p1_grow_anim_4_TILECOUNT 16

#define p2_grow_anim_2_TILECOUNT 16

#define help_2_TILECOUNT 86

#define help_1_TILECOUNT 81

#define help_3_1_TILECOUNT 74

#define p3_idle_anim_4_TILECOUNT 20

#define MenuProfessors_TILECOUNT 351

#define SelectModeScreen_TILECOUNT 337

#define p2_idle_anim_1_TILECOUNT 20

#define p1_idle_anim_3_TILECOUNT 20

#define p2_grow_anim_3_TILECOUNT 16

#define p3_grow_anim_1_TILECOUNT 16

#define Winner_5_1_TILECOUNT 377

#define Winner_4_1_TILECOUNT 398

#define Winner_6_1_TILECOUNT 393

#define timer_bar_TILECOUNT 8

#define help_3_TILECOUNT 87

#define help_4_TILECOUNT 85

#define miniAtoms2_TILECOUNT 6

#define modeSelectPointer_TILECOUNT 8

#define help_1_1_TILECOUNT 29

#define two_TILECOUNT 32

#define p2_idle_anim_2_TILECOUNT 20

#define Backing_TILECOUNT 6

#define p2_grow_anim_4_TILECOUNT 16

#define p1_idle_anim_4_TILECOUNT 20

#define p3_grow_anim_2_TILECOUNT 16

#define Paused_TILECOUNT 32

#define atom_progress_1_TILECOUNT 6

#define Winner_1_2_TILECOUNT 360

#define Winner_2_2_TILECOUNT 373

#define Winner_3_2_TILECOUNT 395

#define one_TILECOUNT 32

#define p2_idle_anim_3_TILECOUNT 20

#define MiniProfessors_TILECOUNT 48

#define p3_grow_anim_3_TILECOUNT 16

#define p3_idle_anim_1_TILECOUNT 20

#define p1_grow_anim_1_TILECOUNT 16

#define levelup_TILECOUNT 32

#define atom_progress_2_TILECOUNT 6

#define GameOverBacking_TILECOUNT 154

#define p2_idle_anim_4_TILECOUNT 20

#define ChallengeModeBacking_TILECOUNT 20

#define p1_grow_anim_2_TILECOUNT 16

#define p3_idle_anim_2_TILECOUNT 20

#define p3_grow_anim_4_TILECOUNT 16

#define TimeLost_TILECOUNT 32

#define atom_progress_3_TILECOUNT 6

#define LargeNumbers_TILECOUNT 40

#define Numbers_TILECOUNT 10

#define p4_idle_anim_1_TILECOUNT 20

#define p6_idle_anim_3_TILECOUNT 20

#define p4_grow_anim_3_TILECOUNT 16

#define p5_grow_anim_1_TILECOUNT 16

#define three_TILECOUNT 32

#define MiniAtoms_TILECOUNT 6

#define p6_idle_anim_4_TILECOUNT 20

#define p4_idle_anim_2_TILECOUNT 20

#define p4_grow_anim_4_TILECOUNT 16

#define p5_grow_anim_2_TILECOUNT 16

#define p4_idle_anim_3_TILECOUNT 20

#define p6_grow_anim_1_TILECOUNT 16

#define p5_idle_anim_1_TILECOUNT 20

#define p5_grow_anim_3_TILECOUNT 16

#define p6_grow_anim_2_TILECOUNT 16

#define p4_idle_anim_4_TILECOUNT 20

#define p5_idle_anim_2_TILECOUNT 20

#define p5_grow_anim_4_TILECOUNT 16

#define p4_grow_anim_1_TILECOUNT 16

#define p6_grow_anim_3_TILECOUNT 16

#define p5_idle_anim_3_TILECOUNT 20

#define p6_idle_anim_1_TILECOUNT 20

#define p4_grow_anim_2_TILECOUNT 16

#define p6_grow_anim_4_TILECOUNT 16

#define p5_idle_anim_4_TILECOUNT 20

#define p6_idle_anim_2_TILECOUNT 20

#endif
